<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>88e36fd0-701f-47fc-bbca-0331ad0c2602</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetApiSample.Application\DotnetApiSample.Application.csproj" />
    <ProjectReference Include="..\DotnetApiSample.Infrastructure\DotnetApiSample.Infrastructure.csproj" />
  </ItemGroup>

</Project>
