-- Schema for the Products sample.
--
-- Applied by hand:
--   psql -h localhost -U postgres -d dotnet_api_sample -f db/init.sql
--
-- The local docker-compose mount also runs this automatically, but only when the
-- postgres volume is created for the first time.

CREATE TABLE IF NOT EXISTS products (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text          NOT NULL,
    sku        text          NOT NULL UNIQUE,
    price      numeric(18,2) NOT NULL CHECK (price >= 0),
    created_at timestamptz   NOT NULL DEFAULT now()
);

INSERT INTO products (name, sku, price)
VALUES
    ('Espresso Machine', 'ESP-001', 249.00),
    ('Burr Grinder',     'GRD-002',  89.50),
    ('Gooseneck Kettle', 'KTL-003',  45.00)
ON CONFLICT (sku) DO NOTHING;
